117 регистрация авторизация
SergioPetrushin/Study pull request #121
Opened 2024-03-11 21:09 UTC by SergioPetrushin

2024-03-16 05:46 UTC, Ledford1403 requested changes

2024-03-16 05:46 UTC, Ledford1403 commented on backend/src/main/java/ru/study/study/config/MailSenderFactory.java
> +    // btzroofslvikopsl
Почистить от комментариев

2024-03-16 05:46 UTC, Ledford1403 commented on backend/src/main/java/ru/study/study/controller/UserController.java
> +    @PostMapping(
Удалить тестовый сервис

2024-03-16 05:46 UTC, Ledford1403 commented on backend/src/main/java/ru/study/study/service/UserService.java
> +    private boolean verification(String pwd, String mail) {
Разделить на отдельные методы

2024-03-16 05:46 UTC, Ledford1403 commented on backend/src/main/java/ru/study/study/service/UserService.java
> +    public String userCheckEmail(UserCheckEmailRequest request) {
Подобрать другие варианты текстов ошибок

2024-03-16 05:46 UTC, Ledford1403 commented on backend/src/main/java/ru/study/study/service/UserService.java
> +    public String userCheckLogin(UserCheckLoginRequest request) {
Подобрать другой вариант текста ошибок

2024-03-16 05:46 UTC, Ledford1403 commented on backend/src/main/java/ru/study/study/service/domain/UserDomainService.java
> +    public String userLogin(UserLoginRequest request) {
Сложный метод, надо найти пользователя и вытаскивать его пароль

2024-03-16 05:46 UTC, Ledford1403 commented on backend/src/main/resources/db/changelog/patches/2024-03-10/all.xml
> +            <column name="EMAIL_CODE" type="VARCHAR(50)" value="no email_code"/>
Value пусть будет null, тип UUID

2024-03-16 05:46 UTC, Ledford1403 commented on backend/src/main/resources/db/changelog/patches/2024-03-10/all.xml
> +            <column name="PWD_CODE" type="VARCHAR(50)" value="no pwd_code"/>
Value указывать не нужно, тип  UUID

2024-03-17 18:47 UTC, SergioPetrushin commented on backend/src/main/java/ru/study/study/controller/UserController.java
> +    @PostMapping(
Какой именно?

2024-03-17 18:52 UTC, SergioPetrushin commented on backend/src/main/resources/db/changelog/patches/2024-03-10/all.xml
> +            <column name="EMAIL_CODE" type="VARCHAR(50)" value="no email_code"/>
Выполнено

2024-03-17 18:54 UTC, SergioPetrushin commented on backend/src/main/resources/db/changelog/patches/2024-03-10/all.xml
> +            <column name="PWD_CODE" type="VARCHAR(50)" value="no pwd_code"/>
Выполнено

2024-03-17 19:33 UTC, SergioPetrushin commented on backend/src/main/java/ru/study/study/service/UserService.java
> +    public String userCheckEmail(UserCheckEmailRequest request) {
Готово

2024-03-17 19:34 UTC, SergioPetrushin commented on backend/src/main/java/ru/study/study/service/UserService.java
> +    public String userCheckLogin(UserCheckLoginRequest request) {
Готово

2024-03-17 19:35 UTC, SergioPetrushin commented on backend/src/main/java/ru/study/study/service/UserService.java
> +    private boolean verification(String pwd, String mail) {
Каким образом если он и так маленький?

2024-03-30 18:14 UTC, merged